#!/bin/bash
set -e

APP_PASSWORD=$(<$APP_PASSWORD_FILE)

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $APP_USER WITH PASSWORD '$APP_PASSWORD';
    CREATE DATABASE $APP_DB;
    GRANT ALL PRIVILEGES ON DATABASE $APP_USER TO $APP_DB;
EOSQL
